# This is a basic workflow to help you get started with Actions
name: webdriver test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/action_webdriver.yml'
      - 'webdriver_test.py'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    - name: Sign In
      timeout-minutes: 70
      run: |
        python actions_rtt.py
        echo "WEBDRIVER_HEADERS=$(cat headers.txt)" >> $GITHUB_ENV
    - name: 'Get Date'
      run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
